# Generated by Django 2.0.7 on 2018-07-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='用戶名')),
                ('email', models.EmailField(max_length=254, verbose_name='信箱')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('message', models.CharField(max_length=500, verbose_name='留言訊息')),
            ],
            options={
                'verbose_name': '用戶留言訊息',
            },
        ),
    ]
